### ISSUE TITLE
Help button crashes app

### ISSUE THREAD

**Issue by aricooperdavis** [mueller-ma/Coffee#58]
**Describe the bug**
When the "Help" button is pressed the app crashes.

**To Reproduce**
1. Open app 
2. Click on 'Help'
3. App closes immediately

**Expected behavior**
The help dialog should be displayed.

**Screenshots**
n/a

**Device**
 - Device: Realme X2 (RMX1993EX_11_C.13)
 - Android version: 10 (ColorOS v7, RealmeUI v1.0)

**Additional context**
Version 1.12 installed from FDroid

**Comment by mueller-ma** [comment]
Can you capture the stacktrace via adb?

**Comment by aricooperdavis** [comment]
Sure, here you go:

```
05-30 15:19:21.773 22186 22186 E AndroidRuntime: FATAL EXCEPTION: main
05-30 15:19:21.773 22186 22186 E AndroidRuntime: Process: com.github.muellerma.coffee, PID: 22186
05-30 15:19:21.773 22186 22186 E AndroidRuntime: android.content.res.Resources$NotFoundException: Can't find ColorStateList from drawable resource ID #0x7f070019
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at android.content.res.ResourcesImpl.loadColorStateList(ResourcesImpl.java:1151)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at android.content.res.Resources.loadColorStateList(Resources.java:1070)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at android.content.res.TypedArray.getColor(TypedArray.java:519)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2475)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2719)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2102)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:864)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:806)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:693)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at android.app.Dialog.dispatchOnCreate(Dialog.java:436)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at android.app.Dialog.show(Dialog.java:318)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at com.github.muellerma.coffee.MainActivity.openHelp(MainActivity.kt:104)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at com.github.muellerma.coffee.MainActivity.onCreate$lambda-5$lambda-4(MainActivity.kt:58)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at com.github.muellerma.coffee.MainActivity.lambda$3qhwZ_WqNExWc9xrcT3c479DeBQ(Unknown Source:0)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at com.github.muellerma.coffee.-$$Lambda$MainActivity$3qhwZ_WqNExWc9xrcT3c479DeBQ.onClick(Unknown Source:2)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at android.view.View.performClick(View.java:7262)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7224)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at android.view.View.access$3800(View.java:824)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:27726)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:228)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7820)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
05-30 15:19:21.773 22186 22186 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
```

**Comment by mueller-ma** [comment]
Does this crash occur in both dark and light mode of your device?

**Comment by aricooperdavis** [comment]
Yes, it does.

**Comment by mueller-ma** [comment]
Can you please test the following apk?

- Rename it to .apk
- Uninstall Coffee
- Install my apk

[app-debug.zip](https://github.com/mueller-ma/Coffee/files/6585479/app-debug.zip)

**Comment by aricooperdavis** [comment]
Thanks for your help, unfortunately that one still crashes in both light and dark modes, I'll get a stack trace layer today.

**Comment by mueller-ma** [comment]
> I'll get a stack trace later today

No need for that, I'll provide another fix later.

**Comment by mueller-ma** [comment]
[app-debug.zip](https://github.com/mueller-ma/Coffee/files/6608710/app-debug.zip)

**Comment by aricooperdavis** [comment]
Sorry, that's still crashing. Not that it really matters, as the functionality of the app works perfectly!

**Comment by mueller-ma** [comment]
I thought the crash is related to `minify`, but that's not the case. You can uninstall my debug build for now.

**Comment by mueller-ma** [comment]
If someone can reproduce this crash, feel free to open a PR with a fix.

**Comment by mueller-ma** [comment]
The help button has been removed
